# Generated by Django 6.1 on 2026-09-14 14:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('web', 'Web Development'), ('product', 'Product & UX'), ('creative', 'Creative Work')], max_length=20)),
                ('role', models.CharField(max_length=255)),
                ('skills', models.CharField(max_length=255)),
                ('thumbnail', models.URLField(blank=True, default='')),
                ('project_url', models.URLField(blank=True, default='')),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-is_featured', 'title'],
            },
        ),
    ]
