# Generated by Django 6.1 on 2026-09-21 16:56

from django.db import migrations, models


def align_legacy_categories(apps, schema_editor):
    experience_model = apps.get_model("main", "Experience")
    category_mapping = {
        "internship": "career",
        "part-time": "career",
        "full-time": "career",
        "freelance": "career",
        "volunteer": "community",
        "research": "personal-project",
    }

    for old_category, new_category in category_mapping.items():
        experience_model.objects.filter(category=old_category).update(
            category=new_category
        )


def restore_legacy_categories(apps, schema_editor):
    experience_model = apps.get_model("main", "Experience")
    category_mapping = {
        "career": "full-time",
        "organizations": "volunteer",
        "community": "volunteer",
        "competition": "research",
        "personal-project": "research",
        "certification": "research",
    }

    for new_category, old_category in category_mapping.items():
        experience_model.objects.filter(category=new_category).update(
            category=old_category
        )


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project'),
    ]

    operations = [
        migrations.RunPython(
            align_legacy_categories,
            restore_legacy_categories,
        ),
        migrations.AlterField(
            model_name='experience',
            name='category',
            field=models.CharField(choices=[('career', 'Career'), ('organizations', 'Organizations'), ('community', 'Community'), ('competition', 'Competition'), ('personal-project', 'Personal Project'), ('certification', 'Certification')], default='career', max_length=20),
        ),
    ]
